### ISSUE TITLE
Expired certificate with https://www.earthref.org

### ISSUE THREAD

**Issue by moonshoes87** [earthref/MagIC#314]
All is well when I go to https://www2.earthref.org, but https://www.earthref.org now gives an expired certificate error:

<img width="829" alt="screen shot 2018-03-02 at 6 35 33 pm" src="https://user-images.githubusercontent.com/1836578/36929653-cd623090-1e48-11e8-9f1c-c4df6d138422.png">

**Comment by rminnett** [comment]
Yes, thanks, @moonshoes87, we've been getting SDSC to update the certificate - hopefully, it'll be fixed tomorrow.

**Comment by rminnett** [comment]
@moonshoes87 I've enabled http://earthref.org without SSL in case you need to reach anything on the earthref.org site.

**Comment by rminnett** [comment]
This should be resolved as of Saturday afternoon.

**Comment by moonshoes87** [comment]
Looks like www.earthref.org works correctly now.  But this link still fails:

https://api.earthref.org/MagIC/vocabularies/data_type.json

I use the vocabularies to make drop down menus for controlled vocabularies.  Are these pages of json no longer available?

**Comment by rminnett** [comment]
@moonshoes87 That url is supposed to be: http://api.earthref.org/MagIC/vocabularies/data_type.json

Elsevier requested access to api.earthref.org endpoints without SSL, but perhaps I could allow both. Is https://api.earthref.org/MagIC/vocabularies/data_type.json hardcoded in PmagPy and already released to users?

**Comment by moonshoes87** [comment]
ok, that fixes it.  Thanks!

**Comment by moonshoes87** [comment]
It appears that earthref.org/MagIC urls don't correctly redirect with www, only with www2.  https://www.earthref.org/MagIC/data-models/3.0

**Comment by rminnett** [comment]
Should work now: https://www.earthref.org/MagIC/data-models/3.0

**Comment by moonshoes87** [comment]
Great, that works.
